services:
  sqlserver:
    image: mcr.microsoft.com/mssql/server:2022-latest
    environment:
      SA_PASSWORD: "FCG@admin"
      ACCEPT_EULA: "Y"
      MSSQL_PID: "Express"
    ports:
      - "1433:1433"
  fcg-api:
    build:
      context: .
      dockerfile: ./FCG.API/Dockerfile
    ports:
      - "5001:8080"
    depends_on:
      - sqlserver
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ConnectionStrings__FCG: "Server=sqlserver;Database=FCG;User=sa;Password=FCG@admin;Initial Catalog=FCG;Integrated Security=True;Encrypt=False;Trust Server Certificate=True"