name: CI

on:
  pull_request:
    branches: [ "main" ]

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Instalar .NET
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.0.x'

      - name: Restaurar dependências
        run: dotnet restore

      - name: Build do projeto
        run: dotnet build --configuration Release --no-restore

      - name: List Test Projects
        run: find . -name "*.csproj" | xargs -I % sh -c 'echo ==== % ====; cat %'

      - name: Rodar testes
        run: dotnet test --no-build --verbosity normal
